#!/bin/sh

if [ "$(id -u)" != "0" ]; then
    exec doas "$0" "$@"
fi

CHROOT=/mnt/glibc

BOX_HOME="/home/user/.local/share/glibc-box-home"

mkdir -p "$BOX_HOME"
mkdir -p "$CHROOT/home/user" "$CHROOT/run/user/1000" "$CHROOT/run/dbus"

exec unshare -m -i sh -c "
    mount --make-rprivate /

    mount --bind $CHROOT $CHROOT

    mount -t proc proc $CHROOT/proc
    mount -t sysfs sys $CHROOT/sys
    
    mount --bind /dev $CHROOT/dev
    mount -o remount,nosuid,nodev $CHROOT/dev
    
    mount --bind /dev/pts $CHROOT/dev/pts
    mount --bind /dev/dri $CHROOT/dev/dri

    mount -t tmpfs -o mode=1777,nosuid,nodev shm $CHROOT/dev/shm

    mount --bind /etc/resolv.conf $CHROOT/etc/resolv.conf

    mount --bind /tmp $CHROOT/tmp
    mount -o remount,nosuid,nodev,noexec $CHROOT/tmp

    mount --rbind /run/user/1000 $CHROOT/run/user/1000
    mount --bind /run/dbus $CHROOT/run/dbus

    mount --bind $BOX_HOME $CHROOT/home/user

    touch $CHROOT/home/user/.Xauthority
    mount --bind /home/user/.Xauthority $CHROOT/home/user/.Xauthority

    ulimit -c 0

    exec chroot $CHROOT env \
        DISPLAY=:0 \
        HOME=/home/user \
        USER=user \
        XAUTHORITY=/home/user/.Xauthority \
        XDG_RUNTIME_DIR=/tmp/runtime-1000 \
        PIPEWIRE_RUNTIME_DIR=/tmp/runtime-1000 \
        PATH=/usr/local/bin:/usr/bin:/bin \
        su user -s /bin/sh -c \"dbus-launch --exit-with-session $*\"
"
